### ISSUE TITLE
End Round Button After Round 1

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#122]
in both tournaments i ran, the end round button for round 1 seems to appear after the time is over or a random amount of time and not after I reported all results?
In round 2 and later, it appears after i reported all results.
Did i miss something?

**Comment by Slanfan** [comment]
Hi. 

There's a background job which monitor all the events that happens to match documents. When you report a match it checks all the other matches for the same round in the same tournament. If all is reported the status of the event will change. All these background jobs lie dormant until needed and starting up may take a few seconds the first time it's needed. That's why you experience a delay the first round but not the other rounds as the worker is now "awake" and ready to do its job. I might consider moving this check client side instead to minimize the "downtime" for organizers.

**Comment by merhans123** [comment]
It showed up faster. Works for me now
