### ISSUE TITLE
Set Event Date & Time to the current date & time by default

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#159]
So when you make an event for the same day, you dont have to do all click.
Maybe you can set starting time also to a time, the most tournaments started in the past.

**Comment by Slanfan** [comment]
I'm not totally agreeing to this. I could add a button to select TODAY and time NOW.
But I'm thinking you should create events in advance and I do not want a lot of events with dates that can´t be found due to organizers missing to set the correct date.

Would buttons to select TODAY and NOW be sufficient enough?

**Comment by merhans123** [comment]
Sounds perfect. 
i understand the problem with „today“ and maybe my case is a fringe case 😅

**Comment by Slanfan** [comment]
![tolaria-issue-159](https://user-images.githubusercontent.com/9950323/107698212-79e69600-6cb4-11eb-9dec-2e4212eb4dfa.gif)

https://github.com/Slanfan/Tolaria/commit/843525a646a498bd6545698c7d5d7aa0d3f60339

**Comment by Slanfan** [comment]
Minor adjustment
![image](https://user-images.githubusercontent.com/9950323/107699014-b8308500-6cb5-11eb-9bcd-e6bbc225d1ea.png)
