### ISSUE TITLE
Change group names

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#253]
I would love to see the option of being able to change the names of the groups/pods.

**Comment by Slanfan** [comment]
I have to give this a thought. Might be possible to add an attribute or property for a custom name even though the core would be letters in the background.

**Comment by lcpdenijs** [comment]
You mean something like an extra field to give the group a certain name?

**Comment by Slanfan** [comment]
Something. As by design, the group letter is only stored on matches and nowhere else so I need to figure out how to apply a name, where to store it and how to get it again. It's just a matter of structuring the code and the templating. But I need to wrap my head around it and maybe discuss it with @JonnieHedkvist
