### ISSUE TITLE
Match Room - Hand size counter

### ISSUE THREAD

**Issue by LoekieMtg** [Slanfan/MTG-Tolaria#259]
I think it would be a great option if you add a counter where you can keep track of you hand size, just like you can now keep digital track of you life and games won.
Especially with online play you don't always see the opponents hand so you either have to keep asking them. 
I now use a die for that, but I figured it would be easier to have a digital counter for that here.

**Comment by lcpdenijs** [comment]
Below is just an idea of where that counter could be

![image](https://user-images.githubusercontent.com/89067536/129920365-14d2424e-b04b-4d7c-b7a4-bb234289e6df.png)

It should look differently then the life counter otherwise people will confuse them with one another, perhaps a logo from a hand could be used to indicate it. Something like this:
![image](https://user-images.githubusercontent.com/89067536/129920504-61e2db84-4b14-4c52-8880-e6610022c138.png)

or this:

![image](https://user-images.githubusercontent.com/89067536/129920708-40085569-27b1-4f37-a357-b93455faf698.png)

**Comment by Slanfan** [comment]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/9950323/192621262-ce0509c4-045b-46ad-84d4-fb65bcf436c0.png">

**Comment by Slanfan** [comment]
Implemented by https://github.com/Slanfan/Tolaria/pull/239/commits/a2f0d65e2d944b866a010ebac79d805ed6894a48
