### ISSUE TITLE
No Video Stream as a spectator

### ISSUE THREAD

**Issue by merhans123** [Slanfan/MTG-Tolaria#338]
I tried cntrl f5, no difference

![image](https://user-images.githubusercontent.com/77571615/146258765-f56af8f3-26ac-40a4-be64-0606ee885133.png)

**Comment by Slanfan** [comment]
Hi. This was most likely due to the fact that only 2 people where in the room. For the stream to start, both players need to be in the room and if the total is 2 then you and a player is there and not that players opponent = match not really started. 

There where a window yesterday where the match-room was broke due to a template error that I fixed as soon as DFB reported it. Might have been in this window you tried to watch.
