### ISSUE TITLE
Manual Pairing Display Issues

### ISSUE THREAD

**Issue by Universe-Inc** [Slanfan/MTG-Tolaria#457]
When setting manual pairings for players it is possible that either a player or a TO has stale data in the interface, when moving to enter the results this data is permanently written into the system's display interface and causes confusion for everyone. It also shows prior round entries incorrectly as well. 

I discovered this issue mostly working with 'bye' players but it should be reproducible whenever a manual pairing is set.

Please see the attached video showing the problem:

https://drive.google.com/file/d/1Uidm871vRi79EeoYwnInGC9aZr1Ik674/view?usp=drivesdk

Here is a screenshot showing the incorrect data display issue. Once a round is completed as well it is locked and no amount of refreshing will correct it: 

https://drive.google.com/file/d/1-w6vc7OM-0yaM02h7uSlZpxq9Tf47_sQ/view?usp=drivesdk

**Comment by Slanfan** [comment]
Awesome. Thanks for reporting this. 

I know exactly what it is now that I see it. 

The match documents are updated live but **ONLY** when the result changes or it becomes reported. 

This is a big issue of course and it's connected to the fact that I back in the days took a decision to keep the life tracking for online matches on the match document. 

With it constantly updating during live events I hade to filter away any "non-important" updates but this also filters away important changes such as new players etc. 

This is a relatively new bug introduced when I changed how the Manual Pairings work. Instead of deleting and creating new matches I now just swap player information. However, this will not update the document in the UI as it's observing pipe filters this away as a "non-relevant" update. 

I'll fix this asap.
