### ISSUE TITLE
Mobile Dashboard - Use BurgerMenu or something similar for left menu

### ISSUE THREAD

**Issue by pietrogalassi** [Slanfan/MTG-Tolaria#98]
In order to have a better UX a burgermenu or something similar that hides itsef is needed.

**Comment by Slanfan** [comment]
Hi. Thanks for the feedback. 
I have no intention to develop the web version for mobile screens as of today. 

Where you not presented with this?

![image](https://user-images.githubusercontent.com/9950323/104225188-5c6ca500-5446-11eb-91b4-cf02e937d5cd.png)

I see one can hit back and login anyways so that I need to fix as this is not the intention due to the fact that I have limited resources to also support mobile friendly web interface. 

But with that said, my end goal is to develop either one or multiple apps which are powered and connected to Tolaria web app for a seamless user experience. 

But native apps are 10000% better on mobile devices than mobile web pages.

**Comment by pietrogalassi** [comment]
I had automatic switch to desktop window and that fooled me
